[project]
name = "clarityxo"
description = "Blockchain Tic-Tac-Toe game on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.clarity-xo-game]
path = "contracts/clarity-xo-game.clar"
clarity_version = 2
epoch = 2.5

[contracts.clarity-xo-trophy]
path = "contracts/clarity-xo-trophy.clar"
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 3
parser_version = 2
