[project]
name = "clarityxo"
description = "Blockchain Tic-Tac-Toe game on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.clarity-xo-game-v2]
path = "contracts/clarity-xo-game-v2.clar"
clarity_version = 2
epoch = 2.5

[contracts.clarityxotrophyv2]
path = "contracts/clarityxotrophyv2.clar"
clarity_version = 2
epoch = 2.5

[contracts.clarityxotrophyv3]
path = "contracts/clarityxotrophyv3.clar"
clarity_version = 2
epoch = 2.5

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 3
parser_version = 2
